# File to be copied in guest as /etc/netplan/02-configure-guest-network.yaml
# Purpose: to provide a network between host and guest for ssh
network:
  version: 2
  ethernets:
    enp0s3:
      addresses: [192.168.64.3/24] # change the IP address as needed
      dhcp4: false