# File to be copied in guest as /etc/netplan/02-configure-guest-network.yaml
# This configures the enp0s4 interface with a static IP 192.168.64.2/24 and also enables DHCP for IPv4.
network:
  version: 2
  ethernets:
    enp0s4:
      addresses: [192.168.64.2/24]
      dhcp4: true